### ISSUE TITLE
生成的亮暗色壁纸并未生效

### ISSUE THREAD

**Issue by dextermo01** [GaiZhenbiao/ChuanhuWallpaper#16]
使用 川虎壁纸 app 生成的亮暗色壁纸，在系统设置里不会根据系统的深色模式切换（Automatic），而是根据时间切换（Dynamic）。

macOS 13.2 下，使用 川虎壁纸 app 生成的亮暗色壁纸，可以在系统设置（System Settings）、墙纸（Wallpaper）、预览图下方看到，变化方式是动态（Dynamic），并且文字描述这样写：“这张墙纸图片全天变化。”（"This wallpaper picture changes thought the day.") 
<img width="473" alt="Screenshot 2023-02-08 at 11 08 57 AM" src="https://user-images.githubusercontent.com/87977513/217628202-b509219d-4f28-41a4-8ebe-dede5f694c5a.png">

而使用达到类似效果的软件 Dynaper app，生成的亮暗色壁纸，变化方式则是自动（Automatic），和系统自带的几张亮暗色墙纸一样，根据系统的深色模式设定进行切换。
<img width="460" alt="Screenshot 2023-02-08 at 11 09 30 AM" src="https://user-images.githubusercontent.com/87977513/217628303-988a3b8b-a34e-45c0-bbd5-6a31d431b3ab.png">

**Comment by Keldos-Li** [comment]
**Good Fist Issue!**

----

经过测试，使用 `川虎壁纸` 生成的亮暗色壁纸，尽管系统设置仅显示为`Dynamic`，但实际运行中还是能做到根据亮暗色切换的……（也就是说，能用，但是显示得不够正确。）

怪我我测试没测完全吧……

原因是，我们曾经觉得Automatic是Dynamic的子集，于是去掉了根据亮暗色切换模式；后面我们又加回来了。可能哪里代码逻辑丢了_(:з」∠)_

**Comment by GaiZhenbiao** [comment]
现在这个问题已经在v2.1.1版里修复了。感谢报告issue～
