### ISSUE TITLE
建议川虎壁纸交互界面

### ISSUE THREAD

**Issue by Keldos-Li** [GaiZhenbiao/ChuanhuWallpaper#9]
### 工具栏
- [x]   删去“工具栏”中的提示、添加图像按钮、导出按钮。
    * _保存图像和macOS共享菜单的逻辑是不同的，不应采用向上的共享图标，也不应放在工具栏中。_
- [ ] 工具栏放置标签页按钮（虽然没啥用），未来可新增黄道计算工具、heic信息提取工具（以及一键分割时间工具……）。
- [x] 主编辑页面下方固定放置导出保存按钮和相关提示信息。

###  侧边栏
- [x] ~~按照Apple深色模式切换重新绘制AppearanceWallpaperView的图标。~~
    * _虽然不建议使用侧边栏，但先用着好了\_(:з」∠)\_。_

###  编辑区
- [x] 使用更准确的拖拽操作文字说明，同时在图形界面中提示拖拽区域（SolarWallpaperView、TimeWallpaperView）。
- [x] 调整AppearanceWallpaperView的布局。
- [x] 调整SolarWallpaperView和TimeWallpaperView的布局。
- [ ] 图片上增加尺寸、大小、格式提示。
    * _考虑原有代码，与交互直接相关的UI未做太多改动。_

## Preview
_本人对代码熟悉度没那么高，所以就不通过SwiftUI实现了。部分UX有参考Equinox和Dynaper。_

![MacBook Pro 13 @2x](https://user-images.githubusercontent.com/23137268/215139733-e661270b-e193-41a3-95ac-33164ee88391.png)
![MacBook Pro 13 @2x-1](https://user-images.githubusercontent.com/23137268/215139744-37634950-08d4-466f-89be-d04f1ca6179d.png)
（TimeWallpaperView的界面与SolarWallpaperView基本一致，不再另做）

您可以在网页中浏览[该Sketch文档](https://sketch.com/s/85bef3f9-d2e4-43db-9707-39732e528602)并在文档中评论。

-------

我觉得对于SwiftUI这种界面和功能代码一起写的语言来说，对界面的共识是在协作中很重要的，避免一个人做了而这个另一个人做了那个……然后产生一些冲突的commit。

所以我建议，在没有大bug的情况下，可以把功能需求和界面框架确定下来再进一步多分支开发。

**Comment by GaiZhenbiao** [comment]
你提的这些都切实际且美观，很有道理。我未来会逐渐实现^_^

**Comment by Keldos-Li** [comment]
😘
 @LiYanan2004 会接着帮忙吗，要不要一起看看(´・ω・`)

**Comment by LiYanan2004** [comment]
@Keldos-Li 本来就有这样的计划哈哈 好多地方都感觉不太合理

**Comment by LiYanan2004** [comment]
昨天试过List的方案就是想去掉那三个按钮 但是想想还是维持比原来的设计比较好 一改的话改动太大了

**Comment by Keldos-Li** [comment]
> 昨天试过List的方案就是想去掉那三个按钮 但是想想还是维持比原来的设计比较好 一改的话改动太大了

这是当时1月14日的草图（川虎哥也看过了），但是发现苹果没有给非偏好设置的其他视图提供这种好看样式的tab view，所以还是先用着navigation view。
![image](https://user-images.githubusercontent.com/23137268/215238819-5518b274-f097-45ab-920c-4a65a6886c70.png)

**Comment by LiYanan2004** [comment]
我来试试看 就按你这个设计稿来 好看的👍
